---
title: "SDM"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dismo)
library(rgdal)
library(sf)
library(rasterVis)
library(spocc)
library(ENMeval)
library(ggplot2)
library(fields) 
library(gstat)

library(scales)
library(testthat)
 
asinh_breaks <- function(x) {
  br <- function(r) {
    lmin <- round(log10(r[1]))
    lmax <- round(log10(r[2]))
    lbreaks <- seq(lmin, lmax, by = 1)
    breaks <- 10 ^ lbreaks
  }
  p.rng <- range(x[x > 0], na.rm = TRUE)
  breaks <- br(p.rng)
  if (min(x) <= 0) {breaks <- c(0, breaks)}
  if (sum(x < 0) > 1) { #more negative values that expected from expanding scale that includes zero
    n.rng <- -range(x[x < 0], na.rm = TRUE)
    breaks <- c(breaks, -br(n.rng))
  }
  return(sort(breaks))
}
test_that("asinh_breaks make sense", {
  expect_equal(asinh_breaks(c(-0.05, 0, 1, 101)), c(0, 1, 10, 100))
  expect_equal(asinh_breaks(c(-0.11, -0.05, 0, 1, 101)), c(-0.1, 0, 1, 10, 100))
  expect_equal(asinh_breaks(c(0, 10, 1001)), c(0, 10, 100, 1000))
  expect_equal(asinh_breaks(c(0, 0.05, 0.07, 0.1, 0.2)), c(0, 0.1))
  expect_equal(asinh_breaks(c(0.01, 0.02)), c(0.01))
})
asinh_trans <- function() {
  trans_new("asinh",
            transform = asinh,
            inverse   = sinh,
            breaks = asinh_breaks)
}

```

## Data Import


```{r}
datadir="/Users/adamw/Documents/Work/advising/Angela/data/20180514_Data"

proj="+proj=utm +zone=19 +ellps=WGS84 +datum=WGS84 +units=m +no_defs"
## point data
#OcR <- read_sf(datadir,"EcT1_3r_OcR_pnt")
OcR<-readOGR(datadir,"EcT1_3r_OcR_pnt")

# union points and polygons
OcR_poly<-readOGR(datadir,"EcT1_3r_OcR_plg")
projection(OcR)=proj

## environmental data
dem=raster(list.files(datadir,pattern="DEM_RAW",full=T))
  projection(dem)=proj
  names(dem)="dem"

sponge=!is.na(raster(list.files(datadir,pattern="_DEM_SP",full=T)))
  projection(sponge)=proj
  names(sponge)="sponge"

coral=!is.na(raster(list.files(datadir,pattern="_DEM_C",full=T)))
  projection(coral)=proj
  names(coral)="coral"
  
rock=!is.na(raster(list.files(datadir,pattern="_DEM_IR",full=T)))
  projection(rock)=proj
  names(rock)="rock"

```

## Interpolate DEM

```{r, eval=F}
demd <- data.frame(xyFromCell(dem, 1:ncell(dem)),v=getValues(dem))
demd2=na.omit(demd)
#### Thin plate spline model
tps <- Tps(demd2[,c("x","y")], demd2$v,lon.lat=F)
p <- raster(dem)


tps <- interpolate(p, tps)
tps <- mask(tps, idw)
plot(tps)


## IDW
idwm <- gstat(id = "v", formula = v~1, locations = ~x+y, data=demd, 
            nmax=7, set=list(idp = .5))

gs <- gstat(formula=v~x+y, data=demd)
idw <- interpolate(r, gs)
## [inverse distance weighted interpolation]
idwr <- mask(idw, vr)
plot(idwr)


## Kriging - ordinary kirging
v <- variogram(v~x+y, data=na.omit(demd),na.rm=T)
m <- fit.variogram(v, vgm(1, "Sph", 300, 1))
gOK <- gstat(NULL, "log.zinc", log(zinc)~1, meuse, model=m)
OK <- interpolate(r, gOK)


# use model to predict values at all locations
r=raster(dem)
dem2 <- interpolate(r, idwm,xyOnly=T,na.rm=T)
p <- mask(p, r)

dem2=interpolate(dem)
```

## Terrain Variables

```{r}
slope=terrain(dem,opt="slope",unit="radians")
tpi=terrain(dem,opt="tpi")
rough=terrain(dem,opt="roughness")


env=stack(dem,slope,rough,tpi,sponge,coral,rock)
plot(env)
```

## Plot

```{r}

gplot(env)+
  geom_raster(aes(fill=value))+
  facet_wrap(~variable)+
  geom_point(data=as.data.frame(OcR),aes(x=coords.x1,y=coords.x2))+
  scale_fill_viridis_c(trans="asinh")

```


## EDA

```{r}
bg <- randomPoints(env[[1]],mask=env[[1]], n=10000)%>%as.data.frame()


```

## Fit Distribution Models

```{r}

preds <- ENMevaluate(coordinates(OcR)[,c(1:2)], env, bg.coords=bg, method='jackknife', RMvalues=c(1,2), fc=c('L','LQ','LQP'), parallel=TRUE)

```


## Plot

```{r}
plot(preds@predictions[[which(eval2@results$delta.AICc==0)]], main="Relative occurrence rate")

```


## Evaluate
```{r}
aic.opt <- preds@models[[which(eval2@results$delta.AICc==0)]]
var.importance(aic.opt)

eval.plot(preds@results, 'Mean.AUC', var='Var.AUC')
```
