cleancols <- function(x){
  dplyr::select(x,
                x="Coord._X",
                y="Coord._Y",
                z="Coord._Z",
                # x="Coord._X",
                # y="Coord._Y",
                # z="Coord._Z",
                r=one_of(c("Rf","R")),
                g=one_of(c("Gf","G")),
                b=one_of(c("Bf","B")),
                classn=Classification,
                x_smooth=contains("Coord._X.smooth"),
                y_smooth=contains("Coord._Y.smooth"),
                z_smooth=contains("Coord._Z.smooth"),
                Ny=Ny,
                Nx=Nx,
                Nz=Nz,
                gc=contains("Gaussian_curvature"),
                rough=contains("Roughness"),
                aspect=contains("Dip_direction_(degrees)"),
                density=contains("Volume_density"),
                slope="Dip_(degrees)")
}
